version: '3.7'

services:
  postgres:
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend
  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge
