services:
  api:
    build: backend
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  web:
    build: frontend
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - frontend

  postgres:
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - web
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
