services:
  api:
    build: backend
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - backend
  postgres:
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend
  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge
